### ISSUE TITLE
Suggested strings for blocklist: suck and 5uck

### ISSUE THREAD

**Issue by Extarys** [sqids/sqids-javascript#21]
As the tittle suggest, I'd recommend adding those two to the blocklist:
`suck`
`5uck`

What do you think?

**Comment by 4kimov** [comment]
Hi @Extarys, yeah that might not be a bad idea. I'll close the issue since the main list is located in https://github.com/sqids/sqids-blocklist, but if you'd like to submit a PR there, feel free to do that.

Looks like we already have "sucker", but if we shorten it to what you suggested, it will cover both of these words: https://github.com/sqids/sqids-blocklist/blob/next/data/en.json#L46
