### ISSUE TITLE
Impossible to filter out certain words because they are too short

### ISSUE THREAD

**Issue by romeovs** [sqids/sqids-javascript#25]
I'm using a limited character set to avoid transcription errors: `34ACDEFHJKPRTXY`.

This works great with Sqids and the effective list of profanity is quite small since there aren't that many words that can be formed with this alphabet.

However, also due to the limited character set, the triplet `KKK` shows up fairly often and I would like to block it. For instance: `CPEYJDCYAHPF3AKKKR4DFCTH`

But because the blocklist does not really block short words nested in longer id's, I've had to resolve to adding all of these to the blocklist:
```
3kkk
4kkk
akkk
ckkk
dkkk
ekkk
fkkk
hkkk
jkkk
kkkk
pkkk
rkkk
tkkk
xkkk
ykkk
kkk3
kkk4
kkka
kkkc
kkkd
kkke
kkkf
kkkh
kkkj
kkkk
kkkp
kkkr
kkkt
kkkx
kkky
```

etc. for every short word I want to block.

This is less than ideal. Is there a better way?

**Comment by 4kimov** [comment]
A few ideas:

1. Don't use "k" as part of the alphabet

2. Fork the repo and lower the threshold so that blocking works with shorter IDs

3. Wrap the library in your own code and every time an ID has a triple "k", replace one of the letters with a character that's not in the alphabet. Do the reverse on decoding
